### ISSUE TITLE
build problems with autoconf and ./configure

### ISSUE THREAD

**Issue by Wikinaut** [Flameeyes/unpaper#38]
I cloned your repo and then tried to build unpaper, but it failed. Perhaps you can assist.

```
# autoconf
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:7: error: possibly undefined macro: AM_MAINTAINER_MODE

# ./configure
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
./configure: line 2078: syntax error near unexpected token `1.13'
./configure: line 2078: `AM_INIT_AUTOMAKE(1.13 dist-xz no-dist-gzip foreign subdir-objects)'
```

**Comment by Flameeyes** [comment]
It seems like your system lacks automake. Please install automake and retry by running `autoreconf -fis` rather than `autoconf`.

**Comment by Wikinaut** [comment]
automake _is_ present. I tried ```autoreconf``` - this works. 

I now have to fix some missing libav... dependencies as told by ```./config```


I want to try your unpaper code because the installed ```unpaper 6.1``` (on OpenSuse Tumbleweed)  tells me "unsupported pixel format"

**Comment by Flameeyes** [comment]
I have no idea what/how OpenSUSE is packaging it, but depending on what
file you're using it on, it might be an unsupported format on libav* or a
format with multiple pixel formats and using one I did not implement.
What's the source file?

On Thu, Jun 25, 2015 at 8:44 AM Wikinaut <notifications@github.com> wrote:

> automake *is* present. I tried autoreconf - this works.
>
> I now have to fix some missing libav... dependencies as told by ./config
>
> I want to try your unpaper code because the installed unpaper 6.1 (on
> OpenSuse Tumbleweed) tells me "unsupported pixel format"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flameeyes/unpaper/issues/38#issuecomment-115150453>.
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by Wikinaut** [comment]
Your version could now be compiled. I got the same problem:

unpaper: error: unable to open file test-imag-true-gray-300dpi.png unsupported pixel format

**Comment by Flameeyes** [comment]
Can you send me (as a separate issue) the output of `avprobe` on that file?

**Comment by Wikinaut** [comment]
I don't have ```avprobe```, and when I want to install libav-tools (on Opensuse Tumbleweed) I receive the message that it will be in conflict with ffmpeg 2.6.3.

So at the present I am giving up due to crazyness stemming from ffmpeg/libav, but let me know if you know a different way.

**Comment by Flameeyes** [comment]
ffprobe if you have ffmpeg installed. But then I don't guarantee
compatibility between unpaper and ffmpeg, so ... :/

On Thu, Jun 25, 2015 at 9:33 AM Wikinaut <notifications@github.com> wrote:

> I don't have avprobe, and when I want to install libav-tools (on Opensuse
> Tumbleweed) I receive the message that it will be in conflict with ffmpeg
> 2.6.3.
>
> So at the present I am giving up due to crazyness stemming from
> ffmpeg/libav, but let me know if you know a different way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flameeyes/unpaper/issues/38#issuecomment-115162192>.
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by Wikinaut** [comment]
ffprobe output in http://dpaste.com/0SYH639

**Comment by ppisar** [comment]
This looks like issue #39 where a patch is linked.
