### ISSUE TITLE
[question]: Is the Project dead?

### ISSUE THREAD

**Issue by djusHa** [Flameeyes/unpaper#50]
Hi Flameeyes,

what is the actual state of the Project?

**Comment by Flameeyes** [comment]
Project is as alive or dead as a normal open source project with a single unpaid maintainer. Pull requests will be taken a look it if they pass tests, I'll try to make some time to clean the requests up this week.

The more contacts I receive of "is this dead", the less time I'm likely to spend on it though, as they just sap away motivation.

**Comment by djusHa** [comment]
Sorry, was not my intention to demotivate. Keep up the good work!

**Comment by Jmuccigr** [comment]
Likewise!

If others are like me, I think you may be getting these questions because of the utility of unpaper.
